### ISSUE TITLE
Stop Scan Android ¿bug?

### ISSUE THREAD

**Issue by sabas1080** [google/physical-web#254]
The previous app version of android worked well, but the new version of December 23 stops on the scan and finds not the beacon

Version Android KiKat

Thanks

**Comment by g-ortuno** [comment]
@sabas1080 What phone are you using?

**Comment by sabas1080** [comment]
Moto X 2014 @g-ortuno

**Comment by g-ortuno** [comment]
Fixed by #259

**Comment by g-ortuno** [comment]
FYI a new version of the app which fixed the issue was pushed to the Play Store. Please update to that version and let us know if there are any problems.

**Comment by tolson2000** [comment]
Hi g-ortuno,

Yes, I've been using it. There are new issues that I can not pin down, other than to tell you what the experience has been.

Beacons will now at least show up sometimes, albeit, can take several swipe attempts. When another app is in the foreground, the little icon at the top left of the screen will indicate the correct amount of beacons in the area. Howevver, bringing the PW to the foreground will not immediately show those though and sometimes not all of them.

I get a lot of "PW has stopped responding" notices.

Sometimes the screen will go BLACK and I can not bring up any other apps until it decides to come back. I've had to kill the app several times. Total power down and reboot once. Something is still amiss in the overall functioning since the last reliable version of 1.737.

Today, my Nexus 7 has a notice that a System Update downloaded and read to install 5.0.2.
 I am not sure I want to do this if it leads to additional difficulties. Will upgrading Nexus 7 to 5.0.2 from 4.4.4 fix whatever problems PW is having with Kitkat?
