### ISSUE TITLE
Support Web Manifest in the PWS

### ISSUE THREAD

**Issue by scottjenson** [google/physical-web#321]
Currently the Physical Web Server scrapes the web page for Title/Description. While not many sites support the web manifest, it is an excellent and efficient way for us to get this information. The feature request is that the PWS check if a target URL has a web manifest and use it if it exists.

**Comment by mmocny** [comment]
@beaufortfrancois Not sure what you mean to continue Francois? Patch has been merged, but perhaps you can address my last comment about `"description"`?

**Comment by beaufortfrancois** [comment]
I was thinking about handling web manifest icons. As you can read at http://www.w3.org/TR/appmanifest/#h-icons-member, the icons member is an array of image objects that can serve as iconic representations of the web application in various contexts. I'm not sure if we should support them as well. WDYT?

The "description" manifest key doesn't exist yet because web manifest needs to support i10n first. Therefore I wouldn't add it yet.

Regarding _perhaps ... "name" could be used as a description?_, I'm not sure as well if that's something we should do. However using "short_name" instead of "name" if it's present seems better. I will push a PR for that.

**Comment by mmocny** [comment]
Hmm, interesting.

If there is no favicon, certainly we should use it.  But if their is a favicon, its not so clear.  The manifest icon is supposed to be for the "app" -- though I guess the same argument can be made for manifest title vs page title.

We'll just have to experiment and see.

**Comment by scottjenson** [comment]
Closing as we're being given the feedback the web manifest isn't the correct place to put data like this.
