### ISSUE TITLE
search functionality

### ISSUE THREAD

**Issue by evren-cilden** [google/physical-web#379]
I met Andreu Ibanez at Android Developer Days at Ankara, Turkey. After his inspiring and enjoyable talk on the Physical-Web project, we had a little chat on possible use-cases. I had a suggestion and he liked the idea and asked me to post it to you. The suggestion is about the application running on the smart phone of users:

The application could have a search functionality for searching only the content of the physical web (searching the contents of the URLs that are published by beacons nearby). Without the search functionality, the user would have to visit all the URLs when he is searching for a special thing. For example, if somebody is shopping at a mall, and is looking for a specific product/offer/discount, he could enter some keywords about what he is looking for, and activate search mode. In the search mode, only the URLs related to his search topics would be listed on his screen. The URL list could also be weighted and sorted according to relevance to the search entries.

**Comment by mmocny** [comment]
This is a neat idea.  I've had somewhat similar musings in the past, though perhaps not 100% your use case.  Still, here are some thoughts:

1. I've heard people refer to this use case as "triggers", where something reacts automatically to a nearby beacon.
2. We think this is a case better left to userland applications build on-top of the physical web, rather than building it into the physical web layer itself.

Specifically, for your example, heres a vision:

You walk into the mall the first time, and you discover the mall directory url.  This points to a site with a mall map and a list of stores and sales, etc.  One of the options provided is to add a "trigger" for some event (i.e. pass by store X), and you put your phone away.  This app now has the ability to listen for beacons and alert you when your proximity criteria are met (note: this feature is not yet available to the web, but we are considering ways to add it -- today you would have to build a native app for this).

Similarly, if you wanted to be alerted when next nearby a particular Widget, maybe you would go to the manufacturer's website and set a trigger via that.

Also, it's not entirely even clear to me that the proximity trigger beacons should be broadcasting urls, this may be a base better suited to broadcasting uuids..

**Comment by scottjenson** [comment]
The Physical Web, up until now, has been about interacting with the thing in-front-of-you. In that situation, we just want you to get to the reasonably obvious thing you're looking at.

The Mall situation is much different as it implies a domain MUCH bigger than you can receive from BLE beacons. If we'd do the search you suggest from within the visible beacons, you'd only be searching a subset of the Mall. Would the user understand that?

So many times, when we discuss situations like this, we end up concluding that the notifications browser is a very blunt tool and there are lots of competing reasons to expand it. For example, we had a related conversation about how to make museums better (and came to an entirely different feature request for the notifications browser). This is a no-win discussion as there are many situations that would require specific features be added to the notifications browser. We tend to come back to the same point, that the notification browser is indeed a very blunt tool, but one which should stay blunt and it's the web pages that should get smarter. 

So in your case, maybe the user should select the "Mall App" and once there, perform a search. In that case, they are guaranteed to be searching the correct domain. I realize this isn't as magical but it doesn't seem likely that the notification picker can ever meet unique environments specific needs. 

Scott

**Comment by mmocny** [comment]
Thought about this some more, and I think perhaps this is a perfect use case for a feature which you would be willing to install an app for?

If you want to scan around for URLs in the background, and alert you loudly when one fits your search criteria -- why not?  Go for it.  But this is not a desirable behaviour for most users, and so probably should just be separate.

Perhaps this is where you can use our sample apps / sdk to create something specifically for your use case, and "opt-in" for the feature is done via app store download.  Or maybe we can build a sample app for this use case during a future hackathon.

What do you think?

**Comment by evren-cilden** [comment]
I would definitely prefer to install the app having a search functionality. Triggers would serve for a similar purpose but could be disturbing.

Although I am an experienced Java developer I have not yet developed for the Android platform. I think you can build a sample app for this use case during a future hackaton. If I have some spare time I can give it a try...

**Comment by scottjenson** [comment]
We encourage all types of explorations and if you'd like to experiment with a search functionality, please do. Just keep in mind that you would be searching the store's home page, not the store. So, for example, if you search for "Bluetooth headphones" and the electronics store nearby doesn't list that on the home page, the search will fail. For this is properly work, you'd need a searchable database of products, in stock.

**Comment by scottjenson** [comment]
Closing as this thread has quieted down. Please feel free to comment/reopen if needed
