### ISSUE TITLE
Anchor tags are stripped from URLs

### ISSUE THREAD

**Issue by scottjenson** [google/physical-web#556]
Configure a beacon to have a URL with a trailing anchor tag, e.g. 'http://cnn.com#test'

Find the beacon in the Physical Web app, you'll see CNN but notice that the URL looses the tag

Just to be sure, click on the URL and you'll notice that you go to cnn.com

**Comment by scottjenson** [comment]
Turns out that if your url ends in the form "...com/x#test" this is the fail case. If you change it to "...com/x/#test" it then works. So the bug isn't stripping ALL anchor tags

**Comment by nondebug** [comment]
It might be the web server redirecting us.  Clicking the CNN link above in desktop Chrome actually navigates to `http://www.cnn.com/#test`.  I get the same behavior for other sites:

    http://cnn.com#test      -> http://www.cnn.com/#test  
    http://www.cnn.com#test  -> http://www.cnn.com/#test  
    http://jenson.org/m#0000 -> http://jenson.org/m/#0000  

Chrome is smart enough to preserve the anchor tag but it looks like PWS is dropping it when the URL is resolved.

**Comment by mmocny** [comment]
Indeed:

```
$ curl -k -s -H "Content-Type: application/json" -d '{"objects":[{"url":"http://cnn.com#test"}]}' http://url-caster.appspot.com/resolve-scan | python -m json.tool
{
    "metadata": [
        {
            "description": "View the latest breaking news and daily news for U.S., world, weather, entertainment, politics and health at CNN.com.",
            "displayUrl": "http://www.cnn.com/",
            "icon": "https://url-caster.appspot.com/favicon?url=http%3A%2F%2Fi.cdn.turner.com%2Fcnn%2F.e%2Fimg%2F3.0%2Fglobal%2Fmisc%2Fapple-touch-icon.png",
            "id": "http://cnn.com#test",
            "rank": 1000,
            "title": "Breaking News, Daily News and Videos - CNN.com",
            "url": "http://www.cnn.com/"
        }
    ]
}
```

**Comment by mmocny** [comment]
Okay, I think Matt is right.  This is just an interesting case of our url fetcher dropping the hash thinking it isn't needed.

When I set a `goo.gl` short link to redirect to cnn.com#test, I get this curl reply:

```
curl -v http://goo.gl/ucDOPb
... (TEXT OMITTED)
< HTTP/1.1 301 Moved Permanently
... (TEXT OMITTED)
< Location: http://cnn.com/#test
```

But when I curl cnn.com/#test directly, I get:

```
curl -v http://cnn.com/#test
... (TEXT OMITTED)
< HTTP/1.1 301 Moved Permanently
... (TEXT OMITTED)
< Location: http://www.cnn.com/
```

`goo.gl` is returning a hash even though it won't affect the content you fetch, because its trying to actively inform the browser that the user intended to leave the hash in.

`ccn.com` is dropping the hash because it shouldn't affect the content being fetch.

The python/GAE urlfetch util we are using is apparently not doing anything special to track hashes across redirects, and just blindly following `Location:` headers.

I think in order to fix this we may need to manually append the hash at each redirection if it hasn't been preserved.  Alternatively, we may only need to append the hash in the final REST reply, since technically I think the hash should not affect the page content returned from a fetch (unlike get variables).

**Comment by scottjenson** [comment]
Is it clear we need to work around the foibles of a redirector? We *could* just say 'don't use a redirector that drops anchor tags' I'm a bit out of my depth but I'm concerned we may be working too hard to fix this. Once I understoond that my WP installation was redirecting, I was perfectly fine using "/#tag" for my URL

**Comment by mmocny** [comment]
So I think I have a fix which will do, but since it changes the way we return urls we should test with care.

Our existing tests pass and my light pass of manual tests seem ok, but I'd only push this to dev PWS if accepted and try to get everyone to test it out locally for a while.

(As an aside, this work helped me uncover another bug with `groupid` which I patched.  Thankfully that wasn't pushed to the stable server yet, but it shows that we aren't testing DEV enough).

**Comment by mmocny** [comment]
Actually, I think I may have introduced a bug.  This PR will always persist the initiall fragment, but that breaks redirectors which *introduce new* fragments.

I'll change the PR to only overwrite the fragment if we end up without a fragment, and started with something.

**Comment by mmocny** [comment]
Using `/#tag` vs `#tag` for the URL does not appear to make a difference, at least not for `cnn.com`.

Fixing the `goo.gl` case is actually more intricate than I expected, because we need to now introduce hash at each redirection level and not just at the start..

**Comment by mmocny** [comment]
PR has been updated, now works with `http://cnn.com#test`,  `http://goo.gl/ucDOPb`,  and `http://www.cnn.com/#test`


```
$ curl -k -s -H "Content-Type: application/json" -d '{"objects":[{"url":"http://cnn.com#test"},{"url":"http://goo.gl/ucDOPb"},{"url":"http://www.cnn.com/#test"}]}' http://localhost:8080/resolve-scan | python -m json.tool
{
    "metadata": [
        {
            "description": "View the latest breaking news and daily news for U.S., world, weather, entertainment, politics and health at CNN.com.",
            "displayUrl": "http://www.cnn.com/#test",
            "groupid": "1af1c209dba64b7c",
            "icon": "https://url-caster.appspot.com/favicon?url=http%3A%2F%2Fi.cdn.turner.com%2Fcnn%2F.e%2Fimg%2F3.0%2Fglobal%2Fmisc%2Fapple-touch-icon.png",
            "id": "http://cnn.com#test",
            "rank": 1000,
            "title": "Breaking News, Daily News and Videos - CNN.com",
            "url": "http://www.cnn.com/#test"
        },
        {
            "description": "View the latest breaking news and daily news for U.S., world, weather, entertainment, politics and health at CNN.com.",
            "displayUrl": "http://www.cnn.com/#test",
            "groupid": "1af1c209dba64b7c",
            "icon": "https://url-caster.appspot.com/favicon?url=http%3A%2F%2Fi.cdn.turner.com%2Fcnn%2F.e%2Fimg%2F3.0%2Fglobal%2Fmisc%2Fapple-touch-icon.png",
            "id": "http://goo.gl/ucDOPb",
            "rank": 1000,
            "title": "Breaking News, Daily News and Videos - CNN.com",
            "url": "http://www.cnn.com/#test"
        },
        {
            "description": "View the latest breaking news and daily news for U.S., world, weather, entertainment, politics and health at CNN.com.",
            "displayUrl": "http://www.cnn.com/#test",
            "groupid": "1af1c209dba64b7c",
            "icon": "https://url-caster.appspot.com/favicon?url=http%3A%2F%2Fi.cdn.turner.com%2Fcnn%2F.e%2Fimg%2F3.0%2Fglobal%2Fmisc%2Fapple-touch-icon.png",
            "id": "http://www.cnn.com/#test",
            "rank": 1000,
            "title": "Breaking News, Daily News and Videos - CNN.com",
            "url": "http://www.cnn.com/#test"
        }
    ]
}
```

**Comment by ansondtx20** [comment]
This bug still seems to exist.. Using the Goo.gl shortner, I can create a shortened URL that does appear to contain a #tag, but through physical web, the #tag is dropped.  The PW validator OK's the URL as well... I am using Chrome on iOS 10.
