### ISSUE TITLE
Link to a Map / Image

### ISSUE THREAD

**Issue by ihmunro** [google/physical-web#562]
Afternoon

Just thought I would ask a question with regards to the URLs.

For example, if I have a number of Eddy Beacons in a room, I can via Chrome etc. see the links - not a problem there, but wanted to see if it was possible to display a map of current eddy Beacons in the room.

Any ideas or comments would be appreciated.

Iain

**Comment by patrickkeane** [comment]
Your map would probably look a lot like an electron cloud around the
observer's gps coordinates, because there is no way to infer a beacon's
direction only approximate its distance, whether they're Eddystone or not.

*Caveat:* Unless the Eddystone beacon offered the its specific geolocation
(and nobody moved them after configuring and placing them) via the
advertised URL.  But, not as a general rule -- and it has really nothing to
do with BLE at all.  For some very specific use-cases, that may make sense
however?

A while back I experimented with triangulation using three beacons and
signal strength/loss to estimate distance. I found it wildly inaccurate --
primarily due to signal interference from obstructions, even over large
number of samples. Obstructions as simple as how the phone is held in
addition to nearby physical objects had a significant impact on narrowing
the likely position of the observer.

Cheers,
PK

**Comment by patrickkeane** [comment]
It is an interesting question though.  The more I think about it, the more
I think it MAY be possible to do something interesting by using many RSSI
samples of all beacons in a room and their changes relative to each other *as
you move about* to determine some likely *relative *positions (to each
other) -- That and a whole lot of trigonometry.

**Comment by febinsathar** [comment]
I think triangulation would be a bad idea. It is possible to predict the user location via fingerprinting by training a KNN or a Neural network, given we  have enough beacons to cover the area and we have  pre collected the BLE rssi fingerprint as well. Inorder to get it up and running in chrome browser, chrome need to enable support  for javascript api for BLE such that we could collect the available BLE rssi at a given point and predict it realtime.

**Comment by ihmunro** [comment]
Thanks for the feedback - I think everyone is going a little further than I was looking for.

For example - if I had 10 Eddys in a room that had 10 assets, if 5 of those assets leave the building, I was hoping to see a map that still had the 10 Eddys, but 5 would be greyed out because there would be no signal.

Makes sense ?

Iain

**Comment by febinsathar** [comment]
It is possible via an android/ Ios app. But if a web app/ physical web app need to  discover the presence of beacons in a vicinity javascript bluetooth API should have to be enabled  (which is not enabled via default in chrome browser).

**Comment by scottjenson** [comment]
Well, the current Physical Web client assumes beacons are dynamic so only displays the ones it sees (and can be verified by the Physical Web Service) If you wanted something like this, you'd have to write your own client, you'd just have to also ask for a physical location and then store beacon URLs against that location so you could remember what you previously saw (so you could show old ones in grey). The tricky part is that you're likely indoors and GPS is a bit flakey so you'd have to be careful what you registered as a "location".

**Comment by scottjenson** [comment]
If no further comments, I'm closing but please reopen if necessary
