### ISSUE TITLE
Support resolving to different URLs over time

### ISSUE THREAD

**Issue by klesniewski** [google/physical-web#575]
In a scenario, where changing advertised URL should be as easy as possible I am considering assigning each beacon its own, unique URL, which points to another URL, configured through a web interface. Simply unique URLs will be resolved to assigned URLs through 301 redirect, just as the URL shorteners work. The difference from a URL shortener is that you can change the address behind the short URL.

There are 2 issues I can see with that approach. The first one is the proxy's cache - when the URL behind the short URL changes, proxy will still keep old data. What is the time for invalidating resolved URL in cache? How could one update the cache?

Another problem is that when two beacons advertise two different short URLs pointing to the same URL, the same result is listed twice. In a scenario, where larger area is covered with several beacons advertising the same URL (just hidden behind different short URLs), ideally the URL should be listed only once. The client should recognize, that both URLs after resolving are the same and display the closest one (chosen beacon might have impact on statistics).

**Comment by mmocny** [comment]
As discussed in #579, Physical Web clients are intended to deduplicate results based on the final, destination URL.  If you have multiple short URL which all point to the same destination, we should only show one result.

There are PW clients which haven't been updated to do this, but this is the intention.

As for short-url redirectors that are mutable, we would like to support this feature.  I think you can use a combination of cache-control and must-revalidate headers.  Its been awhile since I dug into the details, but this is standard HTTP practice and not specific to Physical Web.

I should state that the current PWS will use cached results for about 1 hour regardless of cache-control headers, but only because we haven't updated to be smarter.  This is something we hope to improve over time.

From your perspective, I think we should support your use case exactly as you describe!  We think it is a very useful one.

**Comment by klesniewski** [comment]
These are great news! Thanks for the response and I think the issue is ready to be closed.
