### ISSUE TITLE
custom title and description of physical web notification

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#595]
Hello

Currently in a physical web notification, we get the default page title and meta description.

If we could change this data to a custom notification style data, then it would add up to more relevancy to a physical web notification.

How can we do it?

My Suggestion 1:
» In eddystone UUID, we register the beacon on google cloud console with proximity beacon API and then add attachment to it.
» The attachment is thus retrieved by the app using nearby messages API.

A similar thing can be done in case of physical web.
» We add the URL in a beacon in Google cloud and also add the custom title and description associated with it.
» when a smart phone comes near a beacon broadcasting a URL, it will fetch this particular title and description and give it as an output.

My Suggestion 2:
» We take up few bytes from the eddystone protocol specification and use them to store the title and description.

**Comment by scottjenson** [comment]
There are two separate issues here: 1) Getting the new notification data and 2) Presenting it

There are numerous ways of getting the data. One our core principles on the Physical Web team is to "use the web whenever possible" so we'd prefer having the notification data come from the web page itself. We could, for example, use JSON+LD (there are other approaches we could debate of course)

The real issue is what you'd like actually show the user. Right now there is a single notification that takes you to a list of items. Are you suggesting that some items display differently from others? Or are you suggesting that some items have their own notification (separate from the one from Chrome?) Both have issues to discuss.

I guess I'd like to know what you're trying to do with this new notification system. Is it just a layout difference or are you trying to get a different behavior? For example, if you'd like to have your own notification (outside of the chrome one) that could easily be abused to create 'notification spam' for the user. I realize we're pretty conservative when it comes to notifying the user but we feel we must. If this gets irritating, we're going to loose users trust.

Scott

**Comment by kanodia** [comment]
Hello Scott

Please allow me to convey my message in a better way.

For *example*, I am transmitting *www.starbucks.com
<http://www.starbucks.com>* as the URL.

My phone looks for physical web pages and say it detects www.starbucks.com
and shows it to me in my physical web present in my chrome.

As a user, this is how it will appear to me presently
[image: Inline images 2]

» Now this does not convey much information to me.
» The text *"Order while you wait"* has been taken from the *metadata
description* of the page( as far as I know) and the title *"Starbucks" *has
been taken from the *title tag*.

Now, say if I can custom define these parameters, for example like this
[image: Inline images 3]

Here, I custom defined the text of the same starbucks URL that my phone's
physical web scanned for.

This adds for relevancy to the URL. A user gets a clear message. Also, it
allows the stores to convey an effective contextual message.

Are we thinking on these lines? Don't you think it will add more meaning to
physical web




*Abhishek Kanodia*
Under Graduate Student
BITS Pilani

**Comment by scottjenson** [comment]
Unfortunately your images didn't come throught. However, in an attempt to keep the conversation going, help me understand. Do you just want to have more control over the Title/description text? If so, you can do that in the web page itself so you have full control. Do you want to offer something *other* than text  (e.g. HTML)? If so, it's not clear what you want.

**Comment by kanodia** [comment]
<img width="256" alt="screen shot 2016-02-23 at 12 58 51 pm" src="https://cloud.githubusercontent.com/assets/8614465/13244843/63d66c4a-da2f-11e5-92bf-5c64d324de14.png">

**Comment by kanodia** [comment]
Hello Scott

Please allow me to convey my message in a better way.

For example, I am transmitting www.starbucks.com as the URL.

My phone looks for physical web pages and say it detects www.starbucks.com and shows it to me in my physical web present in my chrome.

As a user, this is how it will appear to me presently
<img width="256" alt="screen shot 2016-02-23 at 12 58 51 pm" src="https://cloud.githubusercontent.com/assets/8614465/13244914/d55e42c0-da2f-11e5-9bf5-4b1b8199e281.png">

» Now this does not convey much information to me. 
» The text "Order while you wait" has been taken from the metadata description of the page( as far as I know) and the title "Starbucks" has been taken from the title tag.

Now, say if I can custom define these parameters, for example like this
![sb](https://cloud.githubusercontent.com/assets/8614465/13244993/ebf20328-da2f-11e5-9cd9-63c9d8ac4360.jpg)

Here, I custom defined the text of the same starbucks URL that my phone's physical web scanned for.

This adds for relevancy to the URL. A user gets a clear message. Also, it allows the stores to convey an effective contextual message.

Are we thinking on these lines? Don't you think it will add more meaning to physical web

**Comment by scottjenson** [comment]
Sorry but I don't understand why you can't do this with the existing approach. Just change the title of the page or the description field, you can place any text there you wish. You can even dynamically change the values (it will take a few minutes before the cache gets old but you can easily change the value many times per day)

**Comment by kanodia** [comment]
Thank You scott. I agree with the current solution.
The only concern that I have is, will this information change instantly.

I was under the impression that it may take days for this information to
crawl as what happens in googlw web master.
If we update the meta data, google webmaster tool takes time to crawl and
update the results in google search.

So I thought this would be the same in case of physical web

**Comment by scottjenson** [comment]
No, our version of the Physical Web keeps it's own cache and updates after about 5 minutes. This will likely change as we evolve the product. We already have people putting URL Shortened URLs into their beacons which point to a redirector. This allows them to use one beacon in the morning and one in the afternoon.

**Comment by muniriver** [comment]
Dear all
I would like ask yours if you could anwers to this question (apologices for my English)
Could I use a URL pinting to a dynamic HTML page (or even .pHP page) in the way each we could change the page metadata for each request of the PWS?
Thanks in advance

**Comment by scottjenson** [comment]
The issue is simply one of overhead for the PWS. At the moment, it is best of think of the URL as fairly static. This allows the values to be cached. However, we don't cache them forever and people have had some luck with URLs in the morning on others in the afternoon. However, to get the freshness down to minutes (or in your case every refresh would, in effect, require loading your web page for every single user request. Not only does this hammer our server but it significantly delays the UX (as everything has to wait until the PWS gets the full page and parses it.

We appreciate how cool it would be if the PWS were fully dynamic but that requires enormous server power at a scale so we're using some caching to make this work reliable and quickly.

**Comment by EmmanuelSkapple** [comment]
Kanodia How did you solve it? I have the same question

**Comment by kanodia** [comment]
@EmmanuelSkapple : Contact me on mail.
I' LL  guide you through the solution

**Comment by zainapprosoft123** [comment]
Hello,

I also need this custom title and custom description instead of webpage title and meta descritpion, but I don't know how this will solve. 

Android alerts should be customize but its forcefully load default page title and meta description.

Any solution please. help ?????
