### ISSUE TITLE
Is 700 ms still the advisable frequency to be configured in a beacon to get reliable scanning on chrome or nearby API?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#709]

**Comment by scottjenson** [comment]
Yes, but there is nothing magical about the number. The goal is to be able to show all beacons in <2 seconds. 700ms allows you to miss one ad packet, get the second and have 500ms for a round trip to the server to fetch meta data (~2000ms) The interval can be longer, you just run the risk of being slower. In lower power situations, we've seen people use 1000ms just fine.

**Comment by kanodia** [comment]
@scottjenson : So does that mean even if we use 1000ms, physical web scanning would run just fine, be it using chrome or nearby API

**Comment by cco3** [comment]
It will still work, but that isn't to say that you won't run into noticeable differences.

**Comment by kanodia** [comment]
@cco3 : but that isn't to say that you won't run into noticeable differences. 

You mean noticeable difference w.r.t. the battery ?

**Comment by cco3** [comment]
As Scott said, it's going to affect the speed at which you see the beacon (i.e. how quickly a notification pops up).  If you are broadcasting only once a second, and we start scanning just after a broadcast, that's a whole second delay.  If we miss the first broadcast, now we are at two seconds, if we miss the second broadcast, that's 3 seconds.

**Comment by kanodia** [comment]
Wow, thank you for such a simplified explanation.

Hence based on my understanding of what you and Scott said,  if I use a
frequency of 500 ms,  the in that case, even if the third packet is
received,  then theoretically meta data should be shown in 2 seconds thus
achieving the goal.

Am I right to say that?

Also, I have a followup question, what are the factor that can be
responsible for the the phone to miss beacon packets provided it is
intended range of beacon?

**Comment by scottjenson** [comment]
It really is up to each client. In our case, we want to list devices in distance order so we choose 2 seconds to get 'most of them' and rank what we have. If any additional ones arrive, we put them at the end of the list. There are clearly other ways of solving this problem but this presents a much more stable list that doesn't move very much.

Given this approach, you won't get any noticeable difference on anything faster than 700ms as they'll all be within that 2 second window. If you go >700ms you have the chance of being at the end of the list.

However, keep in mind this is just how our Github App does it. Opera's version almost certainly does something different. As more scanning clients show up, we expect these difference to multiply (as they should as it will encourage new, more innovative approaches.

That is why the 700ms is just a suggestion. It's designed to work so that any scanning client can present a stable lists in ~2seconds in *most* cases (it's not a guarantee) So if, for example, you wanted to have a 1500ms beacon, you could, it just runs the risk of being lower on the list. If you are in a situation (like a park) where the beacon count is very low, this could be a perfectly fine trade off.

As to what can cause a beacon to be missed that's hard to say. The BLE driver in the Nexus 5x, for example, was a bit buggy and it just dropped a lot of packets on the floor. In general, in low density environments, most packets are received. We're just planning for the future when the density goes up and congestion will make it harder to receive all packets.

**Comment by kanodia** [comment]
Thank Scott.
So one situation here which is related to the park example:

If there is a spot where there are only few beacons out there say 5. Now, the condition is that the order of list is not at all a concern. So here, using even a low frequency of say 1000ms is as good as using 500 ms or any other lower frequency right?
_____________________ _____________________ _____________________ _________________

The only cause of concern for me is, that if we use low frequency beacon transmitting an URL, than will it show up or not on the Android device, provided it is not a Nexus 5x(the packets are not dropping off)?

**Comment by scottjenson** [comment]
right
