### ISSUE TITLE
Is there any way to see how many devices have been reached by a particular beacon?

### ISSUE THREAD

**Issue by montelco** [google/physical-web#799]
For tracking the breadth of a beacon's reach, is there any way with BLE on with the Physical Web to do this? So for instance if I have one beacon in a certain area maybe I might not reach as many people as I would in another location.

**Comment by scottjenson** [comment]
It's very complicated to figure this out as there are so many factors: antenna design, signal strength and many many environmental factors. All we do in the scanner is to notice it's received signal strength (vs it's broadcast) and order *very roughly* by distance. 

This is one reason why, for a conference, we recommend several beacons with the same URL so you get overlap and can more or less guarantee that everyone can receive the URL.

**Comment by angst7** [comment]
@montelco 
If by breadth of reach you mean how often devices see the beacon (i.e. how good is the foot traffic here), you can get a rough estimate by using a URL forwarder specific to the beacon and watching the PWS hits.  I set up a few PW beacons in a down town area at a business for precisely this reason.  You won't get exact numbers, because the servers only hit a URL once every five minutes or so, but the overall trend data (which days are busy, which times of day are busy) seems to track pretty well with foot traffic in the area.

**Comment by louwng** [comment]
Hi @montelco  may I ask how you recorded the PWS hits, ie how did you set it up to get the PWS hits
