### ISSUE TITLE
Chrome reports no pages found while The Physical Web app finds them

### ISSUE THREAD

**Issue by tymski** [google/physical-web#813]
I have a situation where the Physical Web app shows the URLS from my two Estimote beacons while Chrome refuses to show them in the See What's Nearby screen. This made me pretty sad. 

The device is Sony Experia E2535, with Android 5.0, Chrome 52.

The URLS are google shortened URLS that point to a public service which then redirects to a major retailer's site. 

On another device Chrome displays the URLs in the See What's Nearby screen

![image](https://cloud.githubusercontent.com/assets/1097613/18151321/c3ddd680-7031-11e6-891e-67d538a4ad0c.png)
![image](https://cloud.githubusercontent.com/assets/1097613/18151327/c962c520-7031-11e6-857a-fb277d7b43cb.png)

**Comment by scottjenson** [comment]
I just ran both of these URLs through verify.physical-web.org and they verify properly:
<img width="663" alt="target" src="https://cloud.githubusercontent.com/assets/1055674/18155989/61495aea-6fc7-11e6-8445-e7c1cc341014.png">
<img width="663" alt="target2" src="https://cloud.githubusercontent.com/assets/1055674/18155992/66df2598-6fc7-11e6-918a-3b37798030d9.png">

So that's a good start, the beacons and the website both work fine. The next issue is why aren't they showing up for you. Please not that we've recently shifted scanning from Chrome to Android OS (it has better coverage) If you have the latest Google play services you should be able to go do Settings/Google/Nearby and turn it on there. It should have turned on automatically but this should just force it.

**Comment by tymski** [comment]
Hi Scott, 

Thanks for looking into this. 

Physical Web app displays both urls - that always strongly suggested that the URLs are OK. The problem is Chrome specific.  

I updated Google Play Services, rebooted the phone and nearby picked up one of the URL. 

I don't know why it shows only one of the URLS and why no website logo shown, but I think this issues is resolved.

**Comment by scottjenson** [comment]
The Physical Web supports an open source Physical Web Service as well as Googles, I think we're going to shift the default in the Physical Web app to Google just to avoid this confusion
