### ISSUE TITLE
mDNS on iPhone

### ISSUE THREAD

**Issue by louwng** [google/physical-web#822]
If I send a dns-sd -R .......... Command from terminal on my mac, i dont see the PW url in my PW app on my iphone is it supported in the current version of the PW app?

**Comment by louwng** [comment]
I do pick it up on the mDNS utility on my iphone so i know the mac is transmitting it

**Comment by hayesjordan** [comment]
Unfortunately mDNS is only supported in the latest version of the Android PW app.

**Comment by louwng** [comment]
@hayesjordan thanks for the confirmation, i have an old 7 inch Galaxy Tab 4 with Android 4.4.2 installed will it show up the mdns broadcast if i install the latest version of the PW app for android?

**Comment by hayesjordan** [comment]
I think mDNS doesn't work very well on older versions of Android, so it could be that your device won't work for mDNS. I believe it works best on Android N. 

Wi-Fi direct is also going to be unreliable on older versions of Android. While developing the Wi-Fi direct feature in the app, we really only had success while using 2 Android N devices.

Is there a specific reason why you want to use Wi-Fi instead of ble?
