### ISSUE TITLE
New changes is physical web and nearby notifications?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#854]
Hello

In the recent updates to physical web and nearby notification, I have observed changes w.r.t. the design?

> Physical web URL and nearby notifications only display title and not meta description

What is the reason for dropping the description part of the notification? I think they were actually useful in providing contextual information.

Are we planning to make more design changes like this in future?

Regards

**Comment by scottjenson** [comment]
The description is indeed a useful bit of information. GIven there was so little room in the Notification, we initially showed the Title/Description. The security team felt it was important to show the Title/URL as it gave more information to the user w/r/t the validity of the site. Please keep in mind that there is very little room in the notification, you can't show all three. 

However, when Nearby made that change, they also removed the description from the listview. That was not intended and will be fixed in the next release of Google Play Services (approximately end of January)
