### ISSUE TITLE
Is the issue of nearby notifications resolved?

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#855]
Hello

Some time back nearby notifications were muted due to a bug.

I believe recently a new version of google play services version 10.0.4 has been released. Plus, the nearby notification is temporarily muted message is no more there on the landing page.

Is the issue resolved?

Also, I tried sending two nearby notification messages using a single beacon? What I can see is only one notification inside Google settings>Nearby?

What I know is, we can upload any number of notification in a single UUID?
Is this an issue or a recent developments made to this?

Thanks
Regards

**Comment by scottjenson** [comment]
The description is indeed a useful bit of information. Given there was so
little room in the Notification, we initially showed only the
Title/Description. The security team felt it was important to show the
Title/URL as it gave more information to the user w/r/t the validity of the
site.

However, when Nearby made that change, they also removed the description
from the listview. That was not intended and will be fixed in the next
release of Google Play Services (approximately end of January)

On Thu, Nov 17, 2016 at 11:17 PM, Abhishek Kanodia <notifications@github.com

**Comment by jrmadvertising** [comment]
Hi Scott, 

Are there any plans add a Scan for Nearby Beacons on demand with an icon tap from the home screen?

Happy Thanksgiving!

**Comment by scottjenson** [comment]
With Android M and N you can already do this. When you first accept, there
is a prompt to add to home screen. If you didn't do that, you can go to
Nearby (usually through the quick settings icon) and in the menu is an 'add
to home screen' option.

We understand that most casual users won't do this but it's there for
people what want to use it regularly and not rely on the notifications.

Scott
