### ISSUE TITLE
Cleanup: Remove mDisplayUrl from PhysicalWebBroadcastService

### ISSUE THREAD

**Issue by cco3** [google/physical-web#884]
It's not really needed as a field.

**Comment by cco3** [comment]
(You can either do this in the current change you are working on or later)

**Comment by iankchristie** [comment]
@cco3 I'm not sure how to get around this problem:

The advertisingcallback for notifications needs to know the url to display. However, I can't pass it in as a parameter because the method signature is overridden. I think the displayurl has to be an instance field for the advertisingcallback to have scoped access to the url.

Thoughts?
